# Generated by Django 3.2.9 on 2021-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
