# Generated by Django 2.0.2 on 2020-04-15 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('arrival', models.CharField(max_length=8, null=True, verbose_name='Arrival')),
                ('day', models.IntegerField(null=True, verbose_name='Day')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('departure', models.CharField(max_length=8, null=True, verbose_name='Departure')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_schedule', to='book.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ac', models.IntegerField(verbose_name='1st AC')),
                ('second_ac', models.IntegerField(verbose_name='2nd AC')),
                ('date', models.DateField(verbose_name='Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_chart', to='book.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=20, verbose_name='Name')),
                ('type', models.CharField(max_length=2, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_tickets', to='book.Car')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_tickets', to='book.Seat_Chart')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_tickets', to='book.Station')),
                ('dest_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_schedule_tickets', to='book.Schedule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='book.Station')),
                ('source_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedule_tickets', to='book.Schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_schedule', to='book.Station'),
        ),
        migrations.AddField(
            model_name='car',
            name='dest',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='car_dest', to='book.Station'),
        ),
        migrations.AddField(
            model_name='car',
            name='source',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='car_source', to='book.Station'),
        ),
    ]
