# Generated by Django 3.2.9 on 2021-11-06 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(null=True, verbose_name='Day')),
                ('departure', models.TimeField(null=True, verbose_name='Departure')),
                ('arrival', models.TimeField(null=True, verbose_name='Arrival')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_schedule', to='book.car')),
            ],
        ),
        migrations.CreateModel(
            name='SeatChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_ac', models.IntegerField(verbose_name='1st AC')),
                ('second_ac', models.IntegerField(verbose_name='2nd AC')),
                ('date', models.DateField(verbose_name='Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_chart', to='book.car')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, verbose_name='Code')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Address')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TypeSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.CharField(max_length=20, verbose_name='Name')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_tickets', to='book.car')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_tickets', to='book.seatchart')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_schedule_tickets', to='book.schedule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedule_tickets', to='book.schedule')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_chart', to='book.typeseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_schedule', to='book.station'),
        ),
        migrations.AddField(
            model_name='car',
            name='dest',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='car_dest', to='book.station'),
        ),
        migrations.AddField(
            model_name='car',
            name='source',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='car_source', to='book.station'),
        ),
    ]
