# Generated by Django 3.2.9 on 2021-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('check_send', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(limit_choices_to={'Verified': True}, to='accounts.Profile')),
            ],
        ),
    ]
